spring:
  application:
    name: HotelManagementSystem
  datasource:
    url: jdbc:mysql://localhost:3306/hotel-management-system3
    username: root
    password:  # No password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  server:
    port: 8080

logging:
  level:
    root: INFO
    com.example: DEBUG

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # 1 day
      refresh-token:
        expiration: 604800000 # 7 days

---

spring:
  config:
    activate:
      on-profile: development
  datasource:
    url: jdbc:mysql://localhost:3306/hotel-management-system3
    username: root
    password:  # No password

---

spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:mysql://prod-db-url:3306/hotel-management-system
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
  server:
    port: ${PORT:8080}
